const test = require('node:test');
const assert = require('node:assert/strict');
const vm = require('node:vm');
const fs = require('node:fs');
const crypto = require('node:crypto');
const path = require('node:path');
const files = ['FeedbackWeb', 'FeedbackLegacyBridge', 'FeedbackSender', 'FeedbackWebSender', 'FeedbackDryRun', 'FeedbackInteraction', 'PermanentWhatsAppLog', 'Code-doPost'];
const original = ['Feedback ID','Submitted At','Order ID','Customer ID','Cook ID','Item Code','Rating / 5','Complaint','Refund','Comments','Follow-up Status','WhatsApp Message ID'];
const now = Date.parse('2026-10-09T12:00:00Z');
function fixture() {
  const props = { CONTROL_TOWER_SPREADSHEET_ID:'COPY_ONLY', FLOW_MENU_API_SECRET:'test-service-secret', FEEDBACK_TOKEN_SIGNING_KEY:'a'.repeat(64), FEEDBACK_WEB_BASE_URL:'https://test.example/feedback/open', FEEDBACK_WEB_TEMPLATE_NAME:'customer_feedback_web_v2_fragment', FEEDBACK_WEB_TEMPLATE_URL:'https://test.example/feedback/open#{{1}}', FEEDBACK_V2_WRITES_ENABLED:'true', WHATSAPP_REQUIRE_VERIFIED_FORWARD:'true', FEEDBACK_LIVE_ENABLED:'true' };
  let execution = 1, lockOwner = null, batches = 0, failBefore = false, failAfter = false, duringBatch = null, sends = 0;
  const tables = new Map(); const add = (name, headers, rows=[], columns=headers.length) => { const s = {name,id:tables.size+1,values:[headers,...rows],maxCols:columns,maxRows:1000}; tables.set(name,s);return s; };
  add('Feedback', original.slice(), [], 12);
  add('Orders',['Order ID','Order Status','Delivery Date','Customer ID','Customer Name'],[['ORD-1','Confirmed',new Date('2026-10-06T00:00:00Z'),'CUST-1','Sameera']]);
  add('Deliveries',['Order ID','Delivery Status','Delivered At','Feedback Status','Feedback Requested At','Feedback Completed At','Routific ID','Feedback Reminder Sent At'],[['ORD-1','Delivered',new Date(now-96*3600000),'Not Sent','','','uuid','historic-reminder']]);
  add('Order Items',['Order ID','Order Status','Fulfilment Status','Item Code (AUTO, INTERNAL)','Qty'],[['ORD-1','', '', 'M1',2],['ORD-1','','','M2',1],['ORD-1','Cancelled','','M3',1],['ORD-1','','Cancelled','M4',1],['ORD-1','','','M5',0],['ORD-1','','','',2],['ORD-1','','','M1',3]]);
  add('Dishes',['Item Code','Cook ID','Dish Name','Menu Kitchen Name','Image URL','Average Rating','Rating Count'],['M1','M2','M3','M4','M5'].map(c=>[c,'PRIVATE-'+c,'Dish '+c,'Public Kitchen','https://www.makitchens.com.au/menu-images/Dish-0001.jpg','','']));
  add('Customers',['Customer ID','Name','Phone','WhatsApp Opt-In'],[['CUST-1','Sameera','0420123456','Y']]);
  add('WhatsApp Log',['Message ID','Order ID','Message Type','Phone','Accepted At','Sent At','Delivered At','Read At','Status','Error Code','Error Details']);
  const clone = x => { if(x instanceof Date)return new Date(x);if(Array.isArray(x))return x.map(clone);if(x&&typeof x==='object')return Object.fromEntries(Object.entries(x).map(([k,v])=>[k,clone(v)]));return x; };
  function wrap(s) { return {
    getSheetId:()=>s.id,getName:()=>s.name,getMaxRows:()=>s.maxRows,getMaxColumns:()=>s.maxCols,getLastRow:()=>s.values.length,getLastColumn:()=>Math.max(...s.values.map(r=>r.length)),
    getDataRange:()=>({getValues:()=>clone(s.values)}),
    getRange:(r,c,n=1,m=1)=>{if(typeof r==='string'){const match=r.match(/^([A-Z]+)(\d+)$/);c=[...match[1]].reduce((a,x)=>a*26+x.charCodeAt(0)-64,0);r=Number(match[2]);}return {getRow:()=>r,getColumn:()=>c,getFormula:()=>s.values[r-1]?.[c-1]?.formula||'',getFormulas:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>s.values[r-1+i]?.[c-1+j]?.formula||'')),getValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>clone(s.values[r-1+i]?.[c-1+j]??''))),getDisplayValues:()=>Array.from({length:n},(_,i)=>Array.from({length:m},(_,j)=>String(s.values[r-1+i]?.[c-1+j]??'')))}}
  }; }
  const book={getId:()=> 'COPY_ONLY',getSheetByName:n=>tables.has(n)?wrap(tables.get(n)):null,getSheets:()=>[...tables.values()].map(wrap),getSpreadsheetTimeZone:()=> 'Australia/Sydney'};
  function apply(requests) {
    const staged = new Map([...tables.entries()].map(([k,s])=>[k,clone(s)]));
    const sheet = id => {const s=[...staged.values()].find(s=>s.id===id);if(!s)throw Error('missing sheet');return s};
    const cell = c => { const v=c.userEnteredValue; if(!v)return '';if('formulaValue'in v)return {formula:v.formulaValue};if('numberValue'in v)return c.userEnteredFormat?.numberFormat?.type==='DATE_TIME'?new Date(Math.round((v.numberValue-25569)*86400000) - 11*3600000):v.numberValue;return v.stringValue??v.boolValue??''; };
    for(const r of requests){
      if(r.addSheet){const p=r.addSheet.properties;if(staged.has(p.title))throw Error('duplicate');staged.set(p.title,{name:p.title,id:p.sheetId,values:[],maxCols:p.gridProperties.columnCount,maxRows:p.gridProperties.rowCount});}
      else if(r.appendDimension){const a=r.appendDimension,s=sheet(a.sheetId);s[a.dimension==='COLUMNS'?'maxCols':'maxRows']+=a.length;}
      else if(r.appendCells){const s=sheet(r.appendCells.sheetId);for(const row of r.appendCells.rows){if(row.values.length>s.maxCols)throw Error('grid overflow');s.values.push(row.values.map(cell));}}
      else if(r.updateCells){const a=r.updateCells,s=sheet(a.range.sheetId);if(a.range.endColumnIndex>s.maxCols||a.range.endRowIndex>s.maxRows)throw Error('grid overflow');a.rows.forEach((row,i)=>{const at=a.range.startRowIndex+i;while(s.values.length<=at)s.values.push([]);row.values.forEach((v,j)=>s.values[at][a.range.startColumnIndex+j]=cell(v));});}
      else throw Error('unsupported batch request');
    }
    tables.clear();for(const [k,v]of staged)tables.set(k,v);
  }
  class ClockDate extends Date {constructor(...args){super(...(args.length?args:[now]));}static now(){return now}static [Symbol.hasInstance](v){return v instanceof Date}}
  const lock={hasLock:()=>lockOwner===execution,tryLock:()=>{if(lockOwner!==null)return false;lockOwner=execution;return true},waitLock:()=>{if(lockOwner!==null)throw Error('lock busy');lockOwner=execution},releaseLock:()=>{assert.equal(lockOwner,execution);lockOwner=null}};
  const c=vm.createContext({Date:ClockDate,Set,Map,URL,console:{log:()=>{},error:()=>{}},CONTROL_TOWER_SPREADSHEET_ID:'COPY_ONLY',recordWhatsAppStatus_:()=>{},SpreadsheetApp:{openById:id=>{assert.equal(id,'COPY_ONLY');return book},flush:()=>{}},LockService:{getScriptLock:()=>lock},PropertiesService:{getScriptProperties:()=>({getProperty:k=>props[k]??null,setProperty:(k,v)=>{props[k]=v},deleteProperty:k=>delete props[k]})},Utilities:{getUuid:()=>crypto.randomUUID(),computeDigest:(_,v)=>[...crypto.createHash('sha256').update(v).digest()],computeHmacSha256Signature:(v,k)=>[...crypto.createHmac('sha256',k).update(v).digest()],base64EncodeWebSafe:v=>Buffer.from(v).toString('base64url'),DigestAlgorithm:{SHA_256:'SHA256'},Charset:{UTF_8:'UTF8'},formatDate:(d,tz,format)=>format.includes('HH:mm:ss.SSS')?new Date(d.getTime()+11*3600000).toISOString().slice(0,-1):d.toISOString().slice(0,10)},ContentService:{MimeType:{JSON:'json',TEXT:'text'},createTextOutput:s=>({text:s,setMimeType(){return this}})},Sheets:{Spreadsheets:{batchUpdate:({requests},id)=>{assert.equal(id,'COPY_ONLY');batches++;if(duringBatch){const f=duringBatch;duringBatch=null;f()}if(failBefore){failBefore=false;throw Error('atomic failure before commit')}apply(requests);if(failAfter){failAfter=false;throw Error('response lost after commit')}}}},UrlFetchApp:{fetch:()=>{sends++;throw Error('NO MESSAGES AUTHORIZED')}},CacheService:{getScriptCache:()=>({get:()=>null,put:()=>{},remove:()=>{}})}});
  for(const name of files)vm.runInContext(fs.readFileSync(path.join(__dirname,'../scripts/'+name+'.gs'),'utf8'),c,{filename:name+'.gs'});
  const run=(expression)=>vm.runInContext(expression,c);
  c.feedbackV2Setup();
  function call(token,action,payload={}){return JSON.parse(c.handleFeedbackWebApiRequest_({postData:{contents:JSON.stringify({secret:props.FLOW_MENU_API_SECRET,token,...payload})}},action).text);}
  const issue=()=>c.getOrCreateFeedbackWebLink_('ORD-1').split('#')[1];
  const payload=()=>({dishes:[{itemCode:'M1',rating:2,skipped:false,comment:'=IMPORTXML("bad")'},{itemCode:'M2',rating:0,skipped:true,comment:''}],deliveryRating:2,overallComment:'+SUM(1,2)',testimonialConsent:true});
  const read=token=>call(token,'feedback_read');
  function submit(token,p=payload()){const data=read(token);assert.equal(data.ok,true);return call(token,'feedback_submit',{submissionId:data.result.submissionId,revision:data.result.revision,submission:p});}
  return {c,run,tables,props,issue,call,read,submit,payload,batches:()=>batches,sends:()=>sends,before:()=>{failBefore=true},after:()=>{failAfter=true},concurrent:fn=>{duringBatch=()=>{const old=execution;execution=2;try{fn()}finally{execution=old}}}};
}
test('guarded setup expands actual 12-column grid and preserves A:L; repeatable',()=>{const f=fixture();assert.equal(f.tables.get('Feedback').maxCols,17);assert.deepEqual(f.tables.get('Feedback').values[0].slice(0,12),original);f.c.feedbackV2Setup();assert.equal(f.tables.get('Feedback').maxCols,17);f.tables.get('Feedback').values[0][12]='User custom header';assert.throws(()=>f.c.feedbackV2Setup(),/CONFIGURATION_ERROR/);});
test('secure issuance stores only hashes; replacement is atomic and rejected',()=>{const f=fixture(),a=f.issue(),b=f.issue();assert.equal(a.length,43);assert.notEqual(a,b);assert.equal(f.read(a).error,'REPLACED');assert.equal(f.read(b).ok,true);assert(!JSON.stringify([...f.tables.values()]).includes(b));});
test('revocation and strict expiry at equality, malformed expiry fails closed',()=>{const f=fixture(),a=f.issue();f.c.feedbackV2RevokeOrderLinks('ORD-1');assert.equal(f.read(a).error,'REVOKED');const b=f.issue();f.tables.get('Feedback V2 Links').values.at(-1)[3]=new Date(now).toISOString();assert.equal(f.read(b).error,'EXPIRED');f.tables.get('Feedback V2 Links').values.at(-1)[3]='not-a-date';assert.equal(f.read(b).error,'EXPIRED');});
test('draft resume across reopen and replacement; drafts never publish ratings',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result,p=f.payload();p.dishes[0].rating=0;p.deliveryRating=0;assert.equal(f.call(a,'feedback_draft',{revision:r.revision,submission:p}).ok,true);assert.deepEqual(f.read(a).result.draft,p);assert.equal(f.tables.get('Feedback').values.length,1);const b=f.issue();assert.deepEqual(f.read(b).result.draft,p);assert.equal(f.read(b).result.submissionId,r.submissionId);});
test('optimistic draft revision prevents stale tab overwrites and completion',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result;f.call(a,'feedback_draft',{revision:r.revision,submission:f.payload()});const changed=f.payload();changed.overallComment='Stale tab would overwrite newer progress';assert.equal(f.call(a,'feedback_draft',{revision:r.revision,submission:changed}).error,'CONFLICT');assert.equal(f.call(a,'feedback_submit',{revision:r.revision,submissionId:r.submissionId,submission:f.payload()}).error,'CONFLICT');assert.equal(f.tables.get('Feedback').values.length,1);});
test('persistent submission ID, repeated completion and new link cannot duplicate',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result;assert.equal(f.call(a,'feedback_submit',{revision:0,submissionId:'wrong',submission:f.payload()}).error,'CONFLICT');assert.equal(f.submit(a).result.status,'COMPLETED');assert.equal(f.call(a,'feedback_submit',{revision:0,submissionId:r.submissionId,submission:f.payload()}).result.alreadyCompleted,true);assert.equal(f.tables.get('Feedback').values.length,4);assert.throws(()=>f.issue(),/INELIGIBLE/);assert.equal(f.tables.get('Deliveries').values[1][3],'Completed');assert.equal(f.tables.get('Deliveries').values[1][7],'historic-reminder');});
test('all feedback rows and completion markers rollback together on failed batch',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result;f.before();assert.equal(f.call(a,'feedback_submit',{revision:r.revision,submissionId:r.submissionId,submission:f.payload()}).error,'TEMPORARY_ERROR');assert.equal(f.tables.get('Feedback').values.length,1);assert.equal(f.tables.get('Feedback V2 Orders').values[1][2],'');assert.equal(f.submit(a).ok,true);assert.equal(f.tables.get('Feedback').values.length,4);});
test('lost response after committed batch is safe to retry with same persistent ID',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result;f.after();assert.equal(f.call(a,'feedback_submit',{revision:r.revision,submissionId:r.submissionId,submission:f.payload()}).error,'TEMPORARY_ERROR');assert.equal(f.tables.get('Feedback').values.length,4);assert.equal(f.call(a,'feedback_submit',{revision:0,submissionId:r.submissionId,submission:f.payload()}).result.alreadyCompleted,true);assert.equal(f.tables.get('Feedback').values.length,4);});
test('overlapping requests contend for the same lock and retry without duplicates',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result;let second;const body={revision:r.revision,submissionId:r.submissionId,submission:f.payload()};f.concurrent(()=>{second=f.call(a,'feedback_submit',body)});assert.equal(f.call(a,'feedback_submit',body).ok,true);assert.equal(second.error,'TEMPORARY_ERROR');assert.equal(f.call(a,'feedback_submit',body).result.alreadyCompleted,true);assert.equal(f.tables.get('Feedback').values.length,4);});
test('overlapping link issuance cannot replace a link while issuance holds lock',()=>{const f=fixture();let error;f.concurrent(()=>{try{f.issue()}catch(e){error=e.message}});const token=f.issue();assert.equal(error,'TEMPORARY_ERROR');assert.equal(f.tables.get('Feedback V2 Links').values.length,2);assert.equal(f.read(token).ok,true);});
test('formula payloads remain string cells, skipped ratings blank, complaint/follow-up preserved',()=>{const f=fixture(),a=f.issue();f.submit(a);const rows=f.tables.get('Feedback').values.slice(1);assert.equal(rows[0][9],'=IMPORTXML("bad")');assert.equal(rows[2][9],'+SUM(1,2)');assert.equal(rows[1][6],'');assert.equal(rows[0][7],'Y');assert.equal(rows[0][10],'Open');assert.equal(rows[2][7],'N');assert.equal(rows[2][10],'Open');assert.equal(rows[0][11],'');assert.equal(rows[2][12],'Y');assert(rows[0][1] instanceof Date);});
test('FB and FDBK ID sequence scans entire Feedback table beyond row 2000',()=>{const f=fixture(),t=f.tables.get('Feedback');for(let i=0;i<2100;i++)t.values.push(['FDBK-'+String(i+1),'','ORD-OTHER']);const a=f.issue();f.submit(a);assert.equal(t.name,'Feedback');assert.equal(f.tables.get('Feedback').values.at(-3)[0],'FB-002101');});
test('historical partial feedback blocks web; legacy resumes without overwriting existing row',()=>{const f=fixture(),a=f.issue();const row=['FDBK-000050',new Date(now-1),'ORD-1','CUST-1','PRIVATE-M1','M1',4,'N','N','historic','None','old-id'];f.tables.get('Feedback').values.push(row);assert.equal(f.read(a).error,'LEGACY_IN_PROGRESS');f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M2'},5,'','None',{id:'legacy-M2'});f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'DELIVERY'},4,'','None',{id:'legacy-delivery'});assert.equal(f.tables.get('Feedback').values.length,4);assert.deepEqual(f.tables.get('Feedback').values[1],row);assert.equal(f.read(a).result.status,'COMPLETED');});
test('new legacy drafts are unpublished and finalise once across web and legacy',()=>{const f=fixture(),a=f.issue();f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M1'},2,'Taste','Open',{id:'legacy-1'});f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M2'},'','Didn\'t try this','None',{id:'legacy-2'});assert.equal(f.tables.get('Feedback').values.length,1);assert.equal(f.read(a).result.draft.dishes[0].comment,'Taste');f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'DELIVERY'},2,'','Open',{id:'legacy-3'});assert.equal(f.submit(a).result.alreadyCompleted,true);assert.equal(f.tables.get('Feedback').values.length,4);assert.equal(f.tables.get('Feedback').values[1][11],'legacy-1');});
test('late legacy ratings cannot overwrite completed web feedback',()=>{const f=fixture(),a=f.issue();f.submit(a);f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M1'},5,'changed','None',{id:'late'});assert.equal(f.tables.get('Feedback').values[1][6],2);f.c.fwLegacyComment_('ORD-1','M1','changed',{id:'late-comment'},'Other');assert.equal(f.tables.get('Feedback').values[1][9],'=IMPORTXML("bad")');});
test('legacy optional comments are plain text, persistent-id deduplicated, and retain low-rating rules',()=>{const f=fixture();f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M1'},2,'Other','Open',{id:'m1'});f.c.fwLegacyComment_('ORD-1','M1','=evil',{id:'comment'},'Other');f.c.fwLegacyComment_('ORD-1','M1','=evil',{id:'comment'},'Other');f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M2'},5,'','None',{id:'m2'});f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'DELIVERY'},2,'','Open',{id:'delivery'});assert.equal(f.tables.get('Feedback').values[1][9],'Other: =evil');assert.equal(f.tables.get('Feedback').values[1][7],'Y');});
test('strict types, lengths, duplicate codes, unknown fields, ratings/consent rejected',()=>{const f=fixture(),a=f.issue();const invalid=[p=>p.dishes[0].rating='5',p=>p.dishes[0].rating=2.2,p=>p.dishes[1].skipped='true',p=>p.testimonialConsent='false',p=>p.overallComment='x'.repeat(1201),p=>p.dishes[0].comment='x'.repeat(601),p=>p.dishes[1].itemCode='M1',p=>p.extra=1,p=>p.dishes[0].cookId='injected',p=>p.deliveryRating=null];for(const change of invalid){const p=f.payload();change(p);assert.equal(f.call(a,'feedback_submit',{revision:0,submissionId:f.read(a).result.submissionId,submission:p}).error,'INVALID_INPUT');}assert.equal(f.tables.get('Feedback').values.length,1);});
test('required source headers, authoritative confirmation, and positive non-cancelled quantities',()=>{const f=fixture(),a=f.issue();assert.deepEqual(f.read(a).result.dishes.map(d=>d.itemCode),['M1','M2']);assert(!JSON.stringify(f.read(a)).includes('PRIVATE-'));f.tables.get('Orders').values[1][1]='Pending';assert.equal(f.read(a).error,'INELIGIBLE');f.tables.get('Orders').values[1][1]='Confirmed';f.tables.get('Order Items').values[0][1]='Item Status';assert.equal(f.read(a).error,'TEMPORARY_ERROR');});
test('sender and read-only diagnostic share exact 96-hour boundary across DST',()=>{const f=fixture(),d=f.tables.get('Deliveries');d.values[1][2]=new Date(now-96*3600000+1);assert.equal(f.c.findFeedbackCandidates_().length,0);assert.equal(f.c.feedbackDryRunForOrder_('ORD-1',false).reason,'BEFORE_96_HOURS');d.values[1][2]=new Date(now-96*3600000);assert.equal(f.c.findFeedbackCandidates_().length,1);const batches=f.batches();assert.equal(f.c.feedbackDryRunForOrder_('ORD-1',false).wouldSend,true);assert.equal(f.batches(),batches);assert.equal(f.sends(),0);f.tables.get('Orders').values[1][1]='Pending';assert.equal(f.c.findFeedbackCandidates_().length,0);assert.equal(f.c.feedbackDryRunForOrder_('ORD-1',false).reason,'ORDER_NOT_CONFIRMED');assert.equal(f.c.getNextDay10am_(new Date('2026-10-03T23:00:00+10:00')).getTime(),Date.parse('2026-10-03T13:00:00Z')+96*3600000);});
test('draft and page/event writes bounded; scanners cannot exhaust browser signal budget',()=>{const f=fixture(),a=f.issue();for(let i=0;i<40;i++)f.read(a);const before=f.batches();assert.equal(f.call(a,'feedback_event',{event:'browser_opened'}).ok,true);assert.equal(f.call(a,'feedback_event',{event:'first_interaction'}).ok,true);for(let i=0;i<20;i++)f.call(a,'feedback_event',{event:'browser_opened'});assert.equal(f.batches()-before,2);for(let i=0;i<20;i++){const p=f.payload();p.overallComment=String(i);assert.equal(f.call(a,'feedback_draft',{revision:i,submission:p}).ok,true)}assert.equal(f.call(a,'feedback_draft',{revision:20,submission:f.payload()}).error,'RATE_LIMITED');});
test('provider receipt timestamps are actual events; missing timestamps not invented, duplicates/out-of-order safe',()=>{const f=fixture(),a=f.issue();const state=f.tables.get('Feedback V2 Orders').values[1];state[16]='wamid-1';f.c.updateWhatsAppLogFromStatus_({id:'wamid-1',status:'read',timestamp:String(now/1000-10)});f.c.registerWhatsAppOutbound_('wamid-1','ORD-1','feedback_request','61420123456',new Date(now));f.c.updateWhatsAppLogFromStatus_({id:'wamid-1',status:'delivered',timestamp:String(now/1000-20)});f.c.updateWhatsAppLogFromStatus_({id:'wamid-1',status:'sent',timestamp:String(now/1000-30)});f.c.updateWhatsAppLogFromStatus_({id:'wamid-1',status:'read',timestamp:String(now/1000-10)});const row=f.tables.get('WhatsApp Log').values[1];assert.equal(row[8],'Read');assert.equal(row[7].getTime(),now-10000);assert.equal(f.tables.get('Feedback V2 Orders').values[1][20],new Date(now-10000).toISOString());const before=f.batches();assert.equal(f.c.updateWhatsAppLogFromStatus_({id:'missing',status:'read'}),false);assert.equal(f.batches(),before);});
test('sender template preparation guarded; durable reservation prevents concurrent duplicate sends',()=>{const f=fixture();f.props.FEEDBACK_V2_SENDER_ENABLED='true';f.props.FEEDBACK_WEB_TEMPLATE_URL_CONFIRMED='true';const resolution=f.c.buildFeedbackQueueSnapshot_()[0];const p=f.c.fwPrepareWebMessage_(resolution);assert.equal(p.payload.template.name,'customer_feedback_web_v2_fragment');assert.equal(p.payload.template.language.code,'en');assert.equal(JSON.stringify(p.payload.template.components[0]),JSON.stringify({type:'body',parameters:[{type:'text',text:'Sameera'},{type:'text',text:'ORD-1'}]}));assert.equal(p.payload.template.components[1].index,'0');assert.equal(p.payload.template.components[1].sub_type,'url');assert.equal(p.payload.template.components[1].parameters[0].text.length,43);assert.throws(()=>f.c.fwPrepareWebMessage_(resolution),/MESSAGE_REQUIRES_RECONCILIATION/);assert.equal(f.sends(),0);});
test('write and sender activation switches fail closed; no automatic cutover',()=>{const f=fixture(),a=f.issue();delete f.props.FEEDBACK_V2_WRITES_ENABLED;assert.equal(f.read(a).error,'TEMPORARY_ERROR');assert.equal(f.c.runFeedbackWebSender_().enabled,false);assert.equal(f.sends(),0);});
test('verified webhook routing rejects unauthenticated receipt injection',()=>{const f=fixture(),before=f.batches();const payload={entry:[{changes:[{value:{statuses:[{id:'fake',status:'read',timestamp:String(now/1000)}]}}]}]};f.c.doPost({parameter:{},postData:{contents:JSON.stringify(payload)}});assert.equal(f.batches(),before);const result=f.c.doPost({parameter:{action:'whatsapp_verified'},postData:{contents:JSON.stringify({secret:f.props.FLOW_MENU_API_SECRET,payload})}});assert.equal(JSON.parse(result.text).ok,true);assert.equal(f.tables.get('WhatsApp Log').values[1][0],'fake');});
test('guarded rating formula expansion preserves blank exclusion, detects changes, stays read-only until explicit expansion',()=>{const f=fixture(),d=f.tables.get('Dishes');d.values[1][5]={formula:'=IFERROR(AVERAGEIFS(Feedback!G2:G2000,Feedback!F2:F2000,A2,Feedback!G2:G2000,"<>"),"")'};d.values[1][6]={formula:'=COUNTIFS(Feedback!F2:F2000,A2,Feedback!G2:G2000,"<>")'};const before=f.batches(),audit=f.c.feedbackV2RatingFormulaAudit();assert.equal(audit.readOnly,true);assert.equal(f.batches(),before);f.c.feedbackV2ExpandRatingRanges(audit.formulas);assert.equal(f.tables.get('Dishes').values[1][5].formula,'=IFERROR(AVERAGEIFS(Feedback!G2:G,Feedback!F2:F,A2,Feedback!G2:G,"<>"),"")');assert.throws(()=>f.c.feedbackV2ExpandRatingRanges(audit.formulas),/CONFLICT/);});
test('acceptance recovery preserves actual orphan receipts and does not send or advance completed status',()=>{const f=fixture();f.props.FEEDBACK_V2_SENDER_ENABLED='true';f.props.FEEDBACK_WEB_TEMPLATE_URL_CONFIRMED='true';const p=f.c.fwPrepareWebMessage_(f.c.buildFeedbackQueueSnapshot_()[0]);f.c.updateWhatsAppLogFromStatus_({id:'wamid-accepted',status:'read',recipient_id:p.recipient,timestamp:String(now/1000-10)});f.c.feedbackV2ReconcileAcceptedMessage('ORD-1',p.attemptId,p.recipient,'wamid-accepted',new Date(now-5000).toISOString());const first=f.tables.get('Feedback V2 Orders').values[1][17];f.c.feedbackV2ReconcileAcceptedMessage('ORD-1',p.attemptId,p.recipient,'wamid-accepted',new Date(now).toISOString());assert.equal(f.tables.get('Feedback V2 Orders').values[1][17],first);assert.equal(f.tables.get('Feedback V2 Orders').values[1][20],new Date(now-10000).toISOString());assert.equal(f.tables.get('WhatsApp Log').values[1][8],'Read');assert.equal(f.tables.get('Deliveries').values[1][7],'historic-reminder');assert.equal(f.sends(),0);const replacement=f.issue();assert.equal(f.read(replacement).ok,true);});
test('overlapping legacy completion and web submission share the same completion lock',()=>{const f=fixture(),a=f.issue();f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M1'},5,'','None',{id:'m1'});f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M2'},5,'','None',{id:'m2'});const r=f.read(a).result;let competing;f.concurrent(()=>{competing=f.call(a,'feedback_submit',{revision:r.revision,submissionId:r.submissionId,submission:f.payload()})});f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'DELIVERY'},4,'','None',{id:'m3'});assert.equal(competing.error,'TEMPORARY_ERROR');assert.equal(f.submit(a).result.alreadyCompleted,true);assert.equal(f.tables.get('Feedback').values.length,4);});
test('duplicate historical item rows fail closed and do not get silently reconciled',()=>{const f=fixture(),a=f.issue(),row=['FB-000001','','ORD-1','','','M1',5];f.tables.get('Feedback').values.push(row.slice(),['FB-000002','','ORD-1','','','M1',4]);assert.equal(f.read(a).error,'TEMPORARY_ERROR');assert.throws(()=>f.c.fwLegacySave_('ORD-1','CUST-1',{itemCode:'M2'},5,'','None',{id:'m2'}),/CONFIGURATION_ERROR/);assert.equal(f.tables.get('Feedback').values.length,3);});
test('diagnostics discard tokens, user text, recipient and exception details',()=>{const f=fixture(),a=f.issue();f.c.feedbackReasonDiagnostic_({stage:'ERROR',parts:[a],recipient:a,error:a,stack:a,orderId:'ORD-1'});assert(!JSON.stringify(f.props).includes(a));assert(!JSON.stringify(f.c.getRecentFeedbackReasonDiagnostics()).includes(a));});
test('default token expiry preserves thirty-day policy; copy ID mismatch blocks all writes',()=>{const f=fixture(),a=f.issue();assert.equal(Date.parse(f.tables.get('Feedback V2 Links').values[1][3])-now,30*86400000);f.props.CONTROL_TOWER_SPREADSHEET_ID='PRODUCTION_WOULD_BE_WRONG';assert.equal(f.read(a).error,'TEMPORARY_ERROR');});

test('draft retry after lost acknowledgement returns current revision without another write',()=>{const f=fixture(),a=f.issue(),r=f.read(a).result,p=f.payload();f.after();assert.equal(f.call(a,'feedback_draft',{revision:r.revision,submission:p}).error,'TEMPORARY_ERROR');const before=f.batches();assert.equal(f.call(a,'feedback_draft',{revision:r.revision,submission:p}).result.revision,1);assert.equal(f.batches(),before);assert.equal(f.read(a).result.draft.overallComment,p.overallComment);});

test('replacement fragment template contract fails closed before writes for submitted v1 or mismatched URLs',()=>{
  const cases=[['FEEDBACK_WEB_TEMPLATE_NAME','customer_feedback_web_v1'],['FEEDBACK_WEB_TEMPLATE_NAME',undefined],['FEEDBACK_WEB_TEMPLATE_URL','https://www.makitchens.com.au/feedback/{{1}}'],['FEEDBACK_WEB_TEMPLATE_URL','https://test.example/feedback/open?token={{1}}'],['FEEDBACK_WEB_TEMPLATE_URL','https://test.example/feedback/open/{{1}}'],['FEEDBACK_WEB_TEMPLATE_URL','https://other.example/feedback/open#{{1}}'],['FEEDBACK_WEB_TEMPLATE_URL',undefined]];
  for(const [key,value] of cases){const f=fixture();f.props.FEEDBACK_V2_SENDER_ENABLED='true';f.props.FEEDBACK_WEB_TEMPLATE_URL_CONFIRMED='true';if(value===undefined)delete f.props[key];else f.props[key]=value;const before=f.batches();assert.throws(()=>f.c.fwPrepareWebMessage_(f.c.buildFeedbackQueueSnapshot_()[0]),/CONFIGURATION_ERROR/);assert.equal(f.batches(),before);assert.equal(f.tables.get('Feedback V2 Links').values.length,1);assert.equal(f.sends(),0);}
});
test('selected production URL contract puts only token in fragment and matches the template expansion',()=>{
  const f=fixture();f.props.FEEDBACK_WEB_BASE_URL='https://www.makitchens.com.au/feedback/open';f.props.FEEDBACK_WEB_TEMPLATE_URL=f.props.FEEDBACK_WEB_BASE_URL+'#{{1}}';f.props.FEEDBACK_V2_SENDER_ENABLED='true';f.props.FEEDBACK_WEB_TEMPLATE_URL_CONFIRMED='true';const p=f.c.fwPrepareWebMessage_(f.c.buildFeedbackQueueSnapshot_()[0]);const token=p.payload.template.components[1].parameters[0].text;const url=new URL(f.props.FEEDBACK_WEB_TEMPLATE_URL.replace('{{1}}',token));assert.equal(url.pathname,'/feedback/open');assert.equal(url.search,'');assert.equal(url.hash,'#'+token);assert.equal(f.read(token).ok,true);assert.equal(f.sends(),0);
});


test('96-hour policy blocks the old 48-hour deadline and permits requests after 96 hours',()=>{
  const f=fixture(),d=f.tables.get('Deliveries');
  d.values[1][2]=new Date(now-48*3600000);
  assert.equal(f.c.findFeedbackCandidates_().length,0);
  assert.equal(f.c.feedbackDryRunForOrder_('ORD-1',false).reason,'BEFORE_96_HOURS');
  assert.equal(f.c.feedbackV2Eligibility_({deliveredAt:d.values[1][2].getTime()},false,now).eligible,false);
  d.values[1][2]=new Date(now-96*3600000-1);
  assert.equal(f.c.findFeedbackCandidates_().length,1);
  assert.equal(f.c.feedbackDryRunForOrder_('ORD-1',false).wouldSend,true);
  assert.equal(f.sends(),0);
});
